web/ask/ask/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from qa.views import test

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('qa.urls'))
]

web/ask/qa/urls.py
from django.conf.urls import url

from . import views

app_name = 'qa'
urlpatterns = [
    url(r'^question/(?P<pk>[0-9]+)/$', views.question, name='question'),
    url(r'^$', views.new_questions, name='new_questions'),
    url(r'^popular/$', views.popular_questions, name='popular_questions'),
    url(r'^ask/$', views.question_add, name='question_add'),
    url(r'^login/$', views.login_view, name='login_url'),
    url(r'^/signup/$', views.sign_up, name='signup')
]

web/ask/qa/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse

# Create your models here.


class QuestionManager(models.Manager):
    def new(self):
        return self.get_queryset().order_by('-id')

    def popular(self):
        return self.get_queryset().order_by('-rating')


class Question(models.Model):
    title = models.CharField(default="", max_length=255)
    text = models.TextField(default="")
    added_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)
    likes = models.ManyToManyField(User)
    author = models.ForeignKey(User, related_name='questions')
    objects = QuestionManager()

    def get_url(self):
        return reverse('qa:question', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Answer(models.Model):
    text = models.TextField()
    added_at = models.DateTimeField(auto_now_add=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User)

    def __str__(self):
        return self.text

web/ask/qa/forms.py
from django import forms
from .models import Question, Answer
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
#form for adding a question


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=20)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean__email(self):
        try:
            User.objects.get(email=self.cleaned_data['email'])
            raise forms.ValidationError('User with this email already exists')
        except User.DoesNotExist:
            return self.cleaned_data['email']

    def clean_username(self):
        try:
            User.objects.get(username=self.cleaned_data['username'])
            raise forms.ValidationError('User with this username already exists')
        except User.DoesNotExist:
            return self.cleaned_data['username']

    def save(self):
        return User.objects.create_user(username=self.cleaned_data['username'],
                                        email=self.cleaned_data['email'],
                                        password=self.cleaned_data['password'])


class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        self._user = authenticate(self.request, username=self.cleaned_data['username'], password=self.cleaned_data['password'])
        if self._user is None:
            raise forms.ValidationError("Username or password are not correct/does not exist")

    def get_user(self):
        return self._user


class AskForm(forms.Form):
    title = forms.CharField(max_length=100)
    text = forms.CharField(widget=forms.Textarea)

    def save(self):
        self.cleaned_data['author'] = self._user
        question = Question(**self.cleaned_data)
        question.save()
        return question


class AnswerForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)
    question = forms.IntegerField(widget=forms.HiddenInput)

    def clean_answer(self):
        question_pk = self.cleaned_data['question']
        try:
            _ = Question.objects.get(pk=question_pk)
        except Question.DoesNotExist:
            raise forms.ValidationError("Could not get the question")
        return question_pk

    def save(self):
        self.cleaned_data['author'] = self._user
        return Answer.objects.create(text=self.cleaned_data['text'],
                                     author=self._user,
                                     question=Question.objects.get(pk=self.cleaned_data['question']))

web/ask/qa/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_GET
from django.core.paginator import Paginator, EmptyPage
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
# Create your views here.

from .models import Question, Answer
from .forms import AskForm, AnswerForm, LoginForm, SignUpForm


def test(request):
    return HttpResponse('OK')


def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            _ = form.save()
            user = authenticate(request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            login(request, user)
            return HttpResponseRedirect(reverse('qa:new_questions'))
    else:
        form = SignUpForm()
    return render(request, 'qa/sign_up.html', {
        'form': form
    })


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        form.request = request
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return HttpResponseRedirect(reverse('qa:new_questions'))
    else:
        form = LoginForm()
    return render(request, 'qa/login.html', {
        'form': form
    })


def question(request, pk):
    q = get_object_or_404(Question, pk=pk)
    user = request.user
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        form._user = user
        if form.is_valid():
            _ = form.save()
            return HttpResponseRedirect(q.get_url())
    else:
        form = AnswerForm(initial={'question': q.pk})
    return render(request, 'qa/question.html', {
        'question': q,
        'form': form
    })


def question_add(request):
    user = request.user
    form = AskForm(request.POST)
    form._user = user
    if request.method == 'POST':
        if form.is_valid():
            q = form.save()
            url = q.get_url()
            return HttpResponseRedirect(url)
    return render(request, 'qa/question_add.html', {
        'form': form
    })


@require_GET
def new_questions(request):
    questions = Question.objects.new()
    limit = 10
    try:
        page = int(request.GET.get('page', 1))
    except ValueError:
        raise 404
    paginator = Paginator(questions, limit)
    paginator.base_url = reverse('qa:new_questions') + "?page="
    try:
        page = paginator.page(page)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    return render(request, 'qa/new_questions.html', {
        'questions': page.object_list,
        'paginator': paginator,
        'page': page
    })


@require_GET
def popular_questions(request):
    questions = Question.objects.popular()
    limit = 10
    try:
        page = int(request.GET.get('page', 1))
    except ValueError:
        raise 404
    paginator = Paginator(questions, limit)
    paginator.base_url = reverse('qa:popular_questions') + "?page="
    try:
        page = paginator.page(page)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    return render(request, 'qa/popular_questions.html', {
        'questions': page.object_list,
        'paginator': paginator,
        'page': page
    })

web/ask/qa/templates/qa/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>
    <!-- Bootstrap -->
    <link type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>

<!-- NAVBAR -->
<nav class="navbar navbar-default">
    <div class="container">

        <!--LOGO -->
        <div class="navbar-header">
            <a href="{% url 'qa:new_questions' %}?page=1" class="navbar-brand">Anwser it!</a>

        </div>

        <!-- Menu Items -->
        <div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'qa:popular_questions' %}">Popular</a></li>
                <li><a href="{% url 'qa:login_url' %}">Login</a></li>
                <li><a href="{% url 'qa:signup' %}">Sign up</a></li>
            </ul>

             <ul class="nav navbar-nav navbar-right">
                 <li>{{ user.username }}</li>
             </ul>

        </div>

    </div>
</nav>




<div class="container">




    <nav aria-label="Page navigation">
        {% block paginator_block %}

        {% endblock %}
    </nav>

    {% block content %}
    {% endblock %}

    {% block question_form_block %} {% endblock %}

    {% block login_block %}{% endblock %}

    {% block sign_up_block %}{% endblock %}
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'bootstrap/js/jquery-3.2.1.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

web/ask/qa/templates/qa/login.html
{% extends 'qa/base.html' %}

{% block login_block %}

    {% for e in form.non_field_errors %}
        <div class="alert alert-danger">{{ e }}</div>
    {% endfor %}
    <form class="form-horizontal" method="post" action="{% url 'qa:login_url' %}">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
                <div class="control-group{% if field.errors %}has-error{% endif %}">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}</div>
                </div>
            {% endfor %}
        </fieldset>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>

{% endblock %}

web/ask/qa/templates/qa/new_questions.html
{% extends 'qa/base.html' %}
{% load static %}

{% block paginator_block %}

    <ul class="pagination">

        {% for p in paginator.page_range %}
            {% if p == page.number %}
                <li class="active">
             {% else %}
                <li>
            {% endif %}
                <a href="{{ paginator.base_url }}{{ p }}">{{ p }}</a>
                </li>
        {% endfor %}

    </ul>

{% endblock %}


{% block content %}
    <link type="text/css" href="{% static 'qa/css/style.css' %}" rel="stylesheet">
    {% for question in questions %}
        <div>
            <a href="{% url 'qa:question' question.id %}"><h2>{{ question.title }}</h2></a>
            <p>{{ question.text }}</p>
        </div>

    {% endfor %}
{% endblock %}

web/ask/qa/templates/qa/popular_questions.html
{% extends 'qa/base.html' %}

{% block paginator_block %}

    <ul class="pagination">

        {% for p in paginator.page_range %}
            {% if p == page.number %}
                <li class="active">
             {% else %}
                <li>
            {% endif %}
                <a href="{{ paginator.base_url }}{{ p }}">{{ p }}</a>
                </li>
        {% endfor %}

    </ul>

{% endblock %}

{% block content %}

    {% for question in questions %}
        <a href="{% url 'qa:question' question.id %}"><h2>{{ question.title }}</h2></a>
        <p>{{ question.text }}</h1>

      <ul>
        {% for answer in question.answer_set.all %}
          <li>{{ answer.text }}</li>
        {% endfor %}
      </ul>
    {% endfor %}

{% endblock %}

web/ask/qa/templates/qa/question.html
{% extends 'qa/base.html' %}

{% block content %}

    <h1>{{ question.title }}</h1>
    <p>{{ question.text }}</h1>

    <ul>
        {% for answer in question.answer_set.all %}
            <li>{{ answer.text }} -- added by {{ answer.author }} -- added at {{ answer.added_at }}</li>
        {% endfor %}
    </ul>

{% endblock %}

web/ask/qa/templates/qa/question_add.html
{% extends 'qa/base.html' %}
{% load static %}

{% block question_form_block %}

    {% for e in form.non_field_errors %}
        <div class="alert alert-danger">{{ e }}</div>
    {% endfor %}
    <form class="form-horizontal" method="post" action="/ask/">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
                <div class="control-group{% if field.errors %}has-error{% endif %}">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}</div>
                </div>
            {% endfor %}
        </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
    </form>


{% endblock %}

web/ask/qa/templates/qa/sign_up.html
{% extends 'qa/base.html' %}

{% block sign_up_block %}

    {% for e in form.non_field_errors %}
        <div class="alert alert-danger">{{ e }}</div>
    {% endfor %}
    <form class="form-horizontal" method="post" action="{% url 'qa:signup' %}">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
                <div class="control-group{% if field.errors %}has-error{% endif %}">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}</div>
                </div>
            {% endfor %}
        </fieldset>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>

{% endblock %}